import React,{useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import{FileUp,Send,Sparkles,Database,Quote}from"lucide-react";
import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
function App(){
 const[messages,setMessages]=useState([{role:"assistant",text:"Upload a document, then ask me anything about it."}]);
 const[question,setQuestion]=useState("");const[busy,setBusy]=useState(false);const[indexed,setIndexed]=useState([]);
 const sessionId=useMemo(()=>crypto.randomUUID(),[]);
 async function upload(event){const file=event.target.files?.[0];if(!file)return;setBusy(true);const body=new FormData();body.append("file",file);try{const response=await fetch(API+"/api/documents",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Upload failed");setIndexed(items=>[...items,{name:data.filename,chunks:data.chunks_indexed}]);}catch(error){alert(error.message);}finally{setBusy(false);}}
 async function ask(event){event.preventDefault();const text=question.trim();if(!text||busy)return;setQuestion("");setMessages(items=>[...items,{role:"user",text}]);setBusy(true);try{const response=await fetch(API+"/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:text,session_id:sessionId})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Request failed");setMessages(items=>[...items,{role:"assistant",text:data.answer,sources:data.sources}]);}catch(error){setMessages(items=>[...items,{role:"error",text:error.message}]);}finally{setBusy(false);}}
 return <main className="shell"><aside><div className="brand"><Sparkles/> Atlas RAG</div><p className="muted">Grounded intelligence for your private knowledge.</p><label className="upload"><FileUp/> {busy?"Working…":"Add knowledge"}<input type="file" accept=".pdf,.txt,.md" onChange={upload}/></label><h3><Database size={16}/> Knowledge base</h3>{indexed.length===0?<p className="empty">No documents indexed.</p>:indexed.map((f,i)=><div className="file" key={i}><b>{f.name}</b><span>{f.chunks} chunks</span></div>)}</aside><section className="chat"><header><div><span className="eyebrow">ENTERPRISE COPILOT</span><h1>Ask your knowledge.</h1></div><span className="status">● grounded mode</span></header><div className="messages">{messages.map((m,i)=><article className={"message "+m.role} key={i}><div className="bubble">{m.text}</div>{m.sources?.length>0&&<div className="sources"><span><Quote size={14}/> Sources</span>{m.sources.map((s,j)=><div className="source" key={j}><b>{s.filename+(s.page?" · p."+s.page:"")}</b><small>{s.excerpt}</small></div>)}</div>}</article>)}{busy&&<div className="typing">Retrieving trusted context…</div>}</div><form onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question about your documents…"/><button disabled={busy||!question.trim()}><Send size={18}/></button></form></section></main>
}
createRoot(document.getElementById("root")).render(<App/>);
